Repository redhat-openshift-ecosystem/release, pull requests merged in 2020-01, with the labels that each got.

#1 Initial prowjobs
  Makefile
  OWNERS
  ci-operator/config/redhat-operator-ecosystem/playground/OWNERS
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/OWNERS
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-postsubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/release/redhat-operator-ecosystem-release-master-presubmits.yaml
Labels: do-not-merge/invalid-owners-file, size/XL

#2 Trigger config-updater
  README.md
Labels: approved, size/XS

#3 Whitespace change to trigger config updater
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master.yaml
Labels: approved, lgtm, size/XS
