Repository redhat-openshift-ecosystem/release, pull requests merged in 2020-03, with the labels that each got.

#12 generate new jobs for build01
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
Labels: approved, lgtm, size/L

#13 jobs: regenerate jobs
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-postsubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/M

#14 jobs: regenerate jobs
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-postsubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test, size/M

#15 Revert "Merge pull request #14 from AlexNPavel/remove-config-spec"
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-postsubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
Labels: lgtm, ok-to-test, size/M

#16 Add myself as top-level approver
  OWNERS
Labels: approved, lgtm, size/XS

#17 Add ci-op configs for roe/playground for CVP jobs
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5-periodics.yaml
Labels: approved, lgtm

#18 Remove unnecessary configresolver flags from jobs
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-postsubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
Labels: approved, lgtm

#19 Use AWS-specific workflow in CVP tests
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5-periodics.yaml
Labels: approved, lgtm

#20 CVP: Add ci-op configs for 4.4
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.4.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.4-periodics.yaml
Labels: approved, lgtm

#21 Switch CVP jobs to optional-operators-cvp-common workflow
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.4.yaml
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5.yaml
Labels: approved, lgtm

#22 Remove duplicated jobs on build01
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.4-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-cvp-ocp-4.5-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-periodics.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-postsubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master-presubmits.yaml
  ci-operator/jobs/redhat-operator-ecosystem/release/redhat-operator-ecosystem-release-master-presubmits.yaml
Labels: approved, lgtm, ok-to-test

#23 Add cluster to ci-op's config
  ci-operator/config/redhat-operator-ecosystem/playground/redhat-operator-ecosystem-playground-master.yaml
Labels: approved, lgtm, ok-to-test
